name: JVM and OS matrix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - 'LICENSE*'
      - '.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'

jobs:
  build:
    concurrency:
      group: pull_request-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.java-version }}
      cancel-in-progress: true
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java-version: [ 21 ] # Latest LTS if not Ubuntu
        include:
          - os: ubuntu-latest
            java-version: 17
          - os: ubuntu-latest
            java-version: 22
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test timefold-solver
        run: mvn -B -Dfull verify
