name: Python JVM and OS matrix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'LICENSE*'
      - '.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'

jobs:
  build:
    concurrency:
      group: pull_request-python-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.java-version }}
      cancel-in-progress: true
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java-version: [ 21 ] # Latest LTS if not Ubuntu
        include:
          - os: ubuntu-latest
            java-version: 17
          - os: ubuntu-latest
            java-version: 22
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'temurin'
          cache: 'maven'

      # Need to install all Python versions in the same run for tox
      - name: Python 3.10, Python 3.11, Python 3.12 Setup
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.10
            3.11
            3.12
          cache: 'pip'
          cache-dependency-path: |
            **/setup.py

      - name: Install tox
        run:
          pip install tox build

      - name: Run tox on Timefold Solver for Python test suite
        run: python -m tox

      - name: Run tox on jpyinterpreter test suite
        working-directory: ./python/jpyinterpreter
        run: python -m tox
